artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Subash7Lingden/repository-cat-vs-dog/raw/main/archive.zip
  local_data_file: artifacts/data_ingestion/archive.zip
  unzip_dir: artifacts/data_ingestion